In [5]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [35]:
all_data = pd.read_csv('light_set.csv')
print(all_data)
print(all_data.iloc[:,0:3].min())
all_input = (all_data.iloc[:,0:3].values /255.0)# 여기서 iloc는 가로 데이터를 가져온다 콜론은 전체줄을 의미하고 즉 0번부터 3번까지 데이터를 가져오라는 뜻
#정규화 0과 1사이로 범위를 맞춰주는것(노말라이징)
all_output = all_data.iloc[:,-1].values
xtrain,xtest,ytrain,ytest = train_test_split(all_input, all_output, test_size=1/3)
print(xtrain)
w_hidden = np.random.rand(3,3)
print(w_hidden)
w_output = np.random.rand(1,3)
print(w_output)
b_hidden = np.random.rand(3,1)
b_output = np.random.rand(1,1)

relu = lambda x : np.maximum(x,0)

logistic = lambda x:1/(1 + np.exp(-x))

def forward_prop(x):
    z1 = w_hidden @ x + b_hidden
    a1 = relu(z1)
    z2 = w_output @ a1 + b_output
    a2 = logistic(z2)
    return z1,a1,z2,a2

test_predictions = forward_prop(xtrain.transpose())[3]
test_comparisons = np.equal((test_predictions>=0.5).flatten().astype(int),ytrain)

accuracy = sum(test_comparisons.astype(int) / xtrain.shape[0])
print(accuracy)

      RED  GREEN  BLUE  LIGHT_OR_DARK_FONT_IND
0       0      0     0                       1
1       0      0   128                       1
2       0      0   139                       1
3       0      0   205                       1
4       0      0   238                       1
...   ...    ...   ...                     ...
1340   95    158   160                       0
1341   96    123   139                       1
1342   97     97    97                       1
1343   99    184   255                       0
1344   99     99    99                       1

[1345 rows x 4 columns]
RED      0
GREEN    0
BLUE     0
dtype: int64
[[0.56078431 0.7372549  0.56078431]
 [0.25098039 0.87843137 0.81568627]
 [0.42352941 0.65098039 0.80392157]
 ...
 [0.54901961 0.54901961 0.54901961]
 [0.80392157 0.41176471 0.78823529]
 [0.64705882 0.16470588 0.16470588]]
[[0.64299959 0.9923131  0.95500231]
 [0.50764995 0.33335741 0.5904699 ]
 [0.301055   0.8300637  0.57390021]]
[[0.34912714 0.45012925 0.15104584